import {
  Injectable,
  BadRequestException,
  NotFoundException,
  Logger,
} from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { Model } from 'mongoose';
import { Resume, ResumeDocument } from './resume.schema';
import { User, UserDocument, UserRole } from '../users/schemas/user.schema';
import { AiCvApiService } from './ai-cv-api.service';
import { UniversitiesService } from '../universities/universities.service';
import * as fs from 'fs';
import * as path from 'path';
import { PDFParse } from 'pdf-parse';
import * as mammoth from 'mammoth';

@Injectable()
export class ResumeService {
  private readonly logger = new Logger(ResumeService.name);
  private appBaseUrl: string;

  constructor(
    @InjectModel(Resume.name) private resumeModel: Model<ResumeDocument>,
    @InjectModel(User.name) private userModel: Model<UserDocument>,
    private readonly aiCvApiService: AiCvApiService,
    private readonly universitiesService: UniversitiesService,
  ) {
    this.appBaseUrl = process.env.APP_BASE_URL || process.env.APP_URL || 'http://api.aiforjob.ai';
  }

  private buildFileUrl(filePath: string): string {
    const normalized = filePath.replace(/\\/g, '/'); // Windows fix
    return `${this.appBaseUrl}/${normalized}`;
  }

  /**
   * Extract plain text from a PDF, DOCX, or TXT file.
   */
  /**
   * Check if a PDF was generated by the AIForJob Resume Builder.
   * Reads PDF metadata (Creator field) and scans text for the hidden marker.
   */
  private async checkPlatformGenerated(filePath: string): Promise<boolean> {
    try {
      const ext = path.extname(filePath).toLowerCase();
      if (ext !== '.pdf') return false;
      const buffer = fs.readFileSync(filePath);
      const pdf = new PDFParse({ data: buffer });
      const data = await pdf.getText() as any;
      // Check both /Creator metadata and the invisible text marker
      const creatorMatch = data.info?.Creator === 'AIForJob-Platform';
      const textMarker = (data.text || '').includes('AIFORJOB-PLATFORM-GENERATED');
      return creatorMatch || textMarker;
    } catch {
      return false;
    }
  }

  private async extractTextFromFile(filePath: string): Promise<string> {
    try {
      const ext = path.extname(filePath).toLowerCase();
      if (ext === '.pdf') {
        const buffer = fs.readFileSync(filePath);
        const pdf = new PDFParse({ data: buffer });
        const data = await pdf.getText();
        const text = data.text?.trim() || '';
        this.logger.log(`📄 Extracted ${text.length} chars from PDF: ${path.basename(filePath)}`);
        return text;
      } else if (ext === '.docx' || ext === '.doc') {
        const result = await mammoth.extractRawText({ path: filePath });
        const text = result.value?.trim() || '';
        this.logger.log(`📄 Extracted ${text.length} chars from DOCX: ${path.basename(filePath)}`);
        return text;
      } else if (ext === '.txt') {
        const text = fs.readFileSync(filePath, 'utf8');
        this.logger.log(`📄 Extracted ${text.length} chars from TXT: ${path.basename(filePath)}`);
        return text;
      }
    } catch (err) {
      this.logger.error(`💥 Failed to extract text from ${filePath}: ${err.message}`);
    }
    return '';
  }

  async uploadResume(
    file: Express.Multer.File,
    jdFile: Express.Multer.File | undefined,
    jdText: string,
    userId: string,
    token?: string
  ) {
    if (!file) {
      throw new BadRequestException('No resume file uploaded');
    }

    // ✅ ENFORCE LIMIT: Check user's subscription or free tier limit
    const user = await this.userModel.findById(userId).populate('subscriptionPlan').exec();

    const isPayg = (user?.subscriptionPlan as any)?.type === 'pay_as_you_go';

    if (isPayg) {
      // ── PAYG: use paygResumesUsed / paygResumesLimit ─────────────────────
      const used  = user?.paygResumesUsed  ?? 0;
      const limit = user?.paygResumesLimit ?? 0;
      if (used >= limit) {
        throw new BadRequestException(
          `You have reached your PAYG monthly limit of ${limit} resume scan${limit !== 1 ? 's' : ''}. ` +
          `Increase your budget in Pay As You Go settings.`
        );
      }
      await this.userModel.findByIdAndUpdate(userId, { $inc: { paygResumesUsed: 1, resumeCount: 1 } });
    } else {
      // ── Regular / Free plan: read limit stamped at purchase time ──────────
      const currentUsage = user?.resumeCount ?? 0;
      // user.resumeLimit is set when plan is purchased; default 5 for free tier
      let limit = user?.resumeLimit ?? 5;

      // ✅ Override for Students: Use University limits if linked
      if (user?.role === UserRole.STUDENT && user?.universityId) {
        try {
          const uni = await this.universitiesService.findById(user.universityId);
          if (uni) {
            limit = uni.resumeLimit;
            // For students, we always allow them to use their uni limits
          }
        } catch (err) {
          this.logger.error(`Failed to fetch university for student limits: ${err.message}`);
        }
      }

      if (currentUsage >= limit) {
        throw new BadRequestException(
          `You have reached your monthly limit of ${limit} resume${limit !== 1 ? 's' : ''}. ` +
          `Upgrade your plan or wait for your limit to reset on the 1st of next month.`
        );
      }
    }

        // ✅ ENFORCE FILE-SIZE LIMIT based on subscription tier
    const planName = (user?.subscriptionPlan as any)?.name?.toString() || '';
    const isPremium =
      user?.subscriptionStatus === 'active' &&
      planName !== 'free_tier_in' &&
      planName !== '';

    const maxFileBytes = isPremium ? 15 * 1024 * 1024 : 5 * 1024 * 1024;
    const maxFileMB    = isPremium ? 15 : 5;
    const maxPages     = isPremium ? 20 : 7;

    if (file.size > maxFileBytes) {
      throw new BadRequestException(
        isPremium
          ? `Your resume is too large (${(file.size / 1024 / 1024).toFixed(1)} MB). Maximum allowed for your plan is ${maxFileMB} MB.`
          : `Your resume is too large (${(file.size / 1024 / 1024).toFixed(1)} MB). Free accounts support resumes up to ${maxFileMB} MB (≈ ${maxPages} pages). Please upgrade your plan to upload larger resumes.`
      );
    }
    const uploadDir = path.dirname(file.path);
    if (!fs.existsSync(uploadDir)) {
      fs.mkdirSync(uploadDir, { recursive: true });
    }

    // ✅ Use AI CV API service to evaluate CV (optional)
    let stats: any = null;
    try {
      stats = await this.aiCvApiService.uploadAndEvaluateCv(
        file.path,
        file.originalname,
        jdText,
        jdFile?.path,
        jdFile?.originalname,
        token,
        maxPages
      );
    } catch (err) {
      this.logger.error('💥 Error calling cv_evaluate:', err.message);
      stats = {};
    }

    let improvement_resume: any = null;

    // ✅ If JD is provided, also call cv_improvement API (optional)
    if (jdFile || jdText) {
      try {
        improvement_resume = await this.aiCvApiService.uploadAndGetImprovements(
          file.path,
          file.originalname,
          jdText,
          jdFile?.path,
          jdFile?.originalname,
          token,
          maxPages
        );
      } catch (err) {
        this.logger.error('💥 Error calling cv_improvement:', err.message);
        improvement_resume = {};
      }
    } else {
      // ✅ NEW: Always call cv_improvement API even without JD for enhanced content
      try {
        improvement_resume = await this.aiCvApiService.uploadAndGetImprovements(
          file.path,
          file.originalname,
          '', // Empty JD text
          undefined, // No JD file
          undefined,
          token,
          maxPages
        );
      } catch (err) {
        this.logger.error('💥 Error calling cv_improvement:', err.message);
        improvement_resume = {};
      }
    }

    const normalizedPath = file.path.replace(/\\/g, '/');
    const resumeUrl = this.buildFileUrl(normalizedPath);

    // ✅ Extract text from file for future use in Ai for job
    let extractedText = stats?.cv_text || improvement_resume?.cv_text || '';
    if (!extractedText || extractedText.length < 50) {
      this.logger.log('📄 cv_text from AI service missing or short. Extracting text from file...');
      extractedText = await this.extractTextFromFile(file.path);
    }
    this.logger.log(`✅ Resume text ready: ${extractedText.length} chars`);
    if (extractedText) {
      this.logger.log(`📃 RESUME PREVIEW: ${extractedText.substring(0, 300)}`);
    }

    // Ensure we never pass null values
    const finalStats = stats || {};
    let finalImprovementResume = improvement_resume || {};

    // ✅ ENHANCEMENT: If the AI failed to extract the name, inject the name from the User's DB record
    if (finalImprovementResume.tailored_resume) {
      if (!finalImprovementResume.tailored_resume.personal_info) {
        finalImprovementResume.tailored_resume.personal_info = {};
      }

      const pInfo = finalImprovementResume.tailored_resume.personal_info;
      const namePlaceholder = (pInfo.name || '').toLowerCase();
      const isPlaceholder = !pInfo.name ||
        namePlaceholder.includes('your name') ||
        namePlaceholder.includes('full name') ||
        namePlaceholder.includes('placeholder') ||
        pInfo.name.includes('[') || // Detects [Your Name]
        pInfo.name.includes(']');

      if (isPlaceholder) {
        pInfo.name = user?.name || 'Your Name';
      }

      // Also sync user email if missing
      if (!pInfo.email && user?.email) {
        pInfo.email = user.email;
      }
    }

    // ✅ Detect if this PDF was generated by our Resume Builder
    const isPlatformGenerated = await this.checkPlatformGenerated(file.path);
    if (isPlatformGenerated) {
      this.logger.log('🏷️  Resume identified as AIForJob-Platform generated — skipping enhance prompt');
    }

    const resume = new this.resumeModel({
      filename: file.originalname,
      path: normalizedPath,
      url: resumeUrl,
      stats: finalStats,
      improvement_resume: finalImprovementResume,
      text: extractedText,
      is_platform_generated: isPlatformGenerated,
      user: userId,
    });

    try {
      await resume.save();
      // Increment monthly usage counter (PAYG users already incremented above in the limit check block)
      const planType = (user?.subscriptionPlan as any)?.type;
      if (planType !== 'pay_as_you_go') {
        await this.userModel.findByIdAndUpdate(userId, { $inc: { resumeCount: 1 } });
      }
    } catch (saveError) {
      this.logger.error('💥 Database save error:', saveError.message);
      throw saveError;
    }

    return resume;
  }

  async getUserResumes(userId: string) {
    const resumes = await this.resumeModel.find({ user: userId }).sort({
      createdAt: -1,
    });

    // Attach URL to each
    return resumes.map((r) => {
      const obj = r.toObject();
      return {
        ...obj,
        url: this.buildFileUrl(obj.path),
      };
    });
  }

  // ✅ PATCH API: improve resume later
  async improveResume(
    resumeId: string,
    jdFile?: Express.Multer.File,
    jdText?: string,
    token?: string
  ) {
    const resume = await this.resumeModel.findById(resumeId);
    if (!resume) {
      throw new NotFoundException('Resume not found');
    }

    try {
      const improvement_resume = await this.aiCvApiService.uploadAndGetImprovements(
        resume.path,
        resume.filename,
        jdText,
        jdFile?.path,
        jdFile?.originalname,
        token
      );

      const finalImprovementResume = improvement_resume || {};

      // ✅ ENHANCEMENT: Inject the name from the User's DB record
      const user = await this.userModel.findById(resume.user).exec();
      if (finalImprovementResume.tailored_resume) {
        if (!finalImprovementResume.tailored_resume.personal_info) {
          finalImprovementResume.tailored_resume.personal_info = {};
        }

        const pInfo = finalImprovementResume.tailored_resume.personal_info;
        const namePlaceholder = (pInfo.name || '').toLowerCase();
        const isPlaceholder = !pInfo.name ||
          namePlaceholder.includes('your name') ||
          namePlaceholder.includes('full name') ||
          namePlaceholder.includes('placeholder') ||
          pInfo.name.includes('[') || // Detects [Your Name]
          pInfo.name.includes(']');

        if (isPlaceholder) {
          pInfo.name = user?.name || 'Your Name';
        }

        if (!pInfo.email && user?.email) {
          pInfo.email = user.email;
        }
      }

      resume.improvement_resume = finalImprovementResume;
      await resume.save();

      return {
        ...resume.toObject(),
        url: this.buildFileUrl(resume.path),
      };
    } catch (err) {
      this.logger.error('💥 Error improving resume:', err.message);

      if (err.message.includes('ECONNREFUSED') || err.message.includes('connect')) {
        return {
          ...resume.toObject(),
          url: this.buildFileUrl(resume.path),
          improvement_status: 'AI service unavailable'
        };
      }

      throw new BadRequestException('Failed to improve CV');
    }
  }

  async saveBuilderData(resumeId: string, userId: string, builderData: Record<string, any>) {
    const resume = await this.resumeModel.findById(resumeId);
    if (!resume) throw new NotFoundException('Resume not found');
    if (resume.user.toString() !== userId) throw new BadRequestException('Unauthorized');
    resume.builder_data = builderData;
    await resume.save();
    return { message: 'Builder data saved', id: resumeId };
  }

  async deleteResume(resumeId: string, userId: string) {
    const resume = await this.resumeModel.findById(resumeId);
    if (!resume) {
      throw new NotFoundException('Resume not found');
    }

    // Verify the resume belongs to the user
    if (resume.user.toString() !== userId) {
      throw new BadRequestException('Unauthorized to delete this resume');
    }

    try {
      // Delete the file from filesystem
      if (fs.existsSync(resume.path)) {
        fs.unlinkSync(resume.path);
      }

      // Delete from database
      await this.resumeModel.findByIdAndDelete(resumeId);

      return {
        message: 'Resume deleted successfully',
        id: resumeId
      };
    } catch (err) {
      this.logger.error('💥 Error deleting resume:', err.message);
      throw new BadRequestException('Failed to delete resume');
    }
  }
}