import React from 'react';
import { Gavel, CheckCircle, AlertCircle, FileText, CreditCard, ShieldAlert, Zap, HelpCircle, MapPin, Mail, Phone } from 'lucide-react';

const TermsOfService = () => {
    const sections = [
        {
            title: "1. Acceptance of Terms",
            icon: <Gavel className="w-6 h-6 text-blue-500" />,
            content: "By accessing or using ai for job (\"the Platform\"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our services. These terms apply to all visitors, users, and others who access or use the Service."
        },
        {
            title: "2. Description of Service",
            icon: <Zap className="w-6 h-6 text-blue-500" />,
            content: "ai for job provides AI-powered tools for resume building, mock interviews, and career preparation. We leverage advanced artificial intelligence to provide feedback and analysis. We reserve the right to modify, suspend, or discontinue any part of the service at any time without prior notice."
        },
        {
            title: "3. User Accounts",
            icon: <CheckCircle className="w-6 h-6 text-blue-500" />,
            content: "To access certain features, you must create an account. You represent and warrant that the information you provide is accurate and complete. You are solely responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account."
        },
        {
            title: "4. Payments & Subscriptions",
            icon: <CreditCard className="w-6 h-6 text-blue-500" />,
            content: (
                <div className="space-y-4">
                    <p>We offer both free and premium subscription tiers. Our premium features are processed through secure payment gateways: **Stripe** and **Razorpay**.</p>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div className="p-4 rounded-xl border border-gray-100 dark:border-gray-800 bg-gray-50 dark:bg-gray-800/50">
                            <span className="font-bold block mb-1">Billing</span>
                            <p className="text-sm">Subscriptions are billed in advance on a recurring basis (monthly/yearly) depending on your selection.</p>
                        </div>
                        <div className="p-4 rounded-xl border border-gray-100 dark:border-gray-800 bg-gray-50 dark:bg-gray-800/50">
                            <span className="font-bold block mb-1">Refunds</span>
                            <p className="text-sm">Refund requests are handled on a case-by-case basis in accordance with local consumer protection laws.</p>
                        </div>
                    </div>
                </div>
            )
        },
        {
            title: "5. Intellectual Property",
            icon: <FileText className="w-6 h-6 text-blue-500" />,
            content: "All content generated by our AI platform, including the analysis algorithms, UI designs, and proprietary code, remains the intellectual property of ai for job. You may use the platform only for personal, non-commercial purposes unless otherwise agreed upon in writing."
        },
        {
            title: "6. Limitation of Liability",
            icon: <ShieldAlert className="w-6 h-6 text-blue-500" />,
            content: "Our AI analysis is designed for educational and preparation purposes. While we strive for accuracy, ai for job does not guarantee employment or specific career outcomes. In no event shall we be liable for any indirect or consequential damages arising from the use of the platform."
        }
    ];

    return (
        <div className="min-h-screen bg-gray-50 dark:bg-gray-950 transition-colors duration-300 font-sans">
            {/* Hero Section */}
            <section className="relative pt-32 pb-20 overflow-hidden bg-white dark:bg-gray-900 border-b border-gray-200 dark:border-gray-800">
                <div className="absolute top-0 right-1/2 translate-x-1/2 w-full h-[400px] bg-blue-500/5 blur-[120px] rounded-full opacity-50 pointer-events-none" />
                <div className="max-w-7xl mx-auto px-6 relative z-10 text-center">
                    <div className="inline-flex items-center px-4 py-1.5 rounded-full border border-blue-500/30 bg-blue-500/10 text-blue-600 dark:text-blue-300 mb-6 backdrop-blur-sm">
                        <Gavel className="w-4 h-4 mr-2" />
                        <span className="text-xs font-bold tracking-widest uppercase">Terms & Agreement</span>
                    </div>
                    <h1 className="text-4xl md:text-6xl font-black text-gray-900 dark:text-white mb-6 tracking-tight">
                        Terms of <span className="text-blue-600">Service</span>
                    </h1>
                    <p className="text-gray-600 dark:text-gray-400 max-w-2xl mx-auto text-lg">
                        Please read these terms carefully before using our platform. They outline your rights and obligations as a user.
                    </p>
                    <p className="mt-8 text-sm font-medium text-gray-400 uppercase tracking-widest">
                        Effective Date: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
                    </p>
                </div>
            </section>

            {/* Content Section */}
            <div className="max-w-5xl mx-auto px-6 py-20">
                <div className="grid grid-cols-1 lg:grid-cols-4 gap-12">
                    {/* Sticky Navigation */}
                    <div className="hidden lg:block lg:col-span-1">
                        <div className="sticky top-32 space-y-4">
                            <h4 className="text-xs font-bold text-gray-400 uppercase tracking-widest mb-6 px-4">Agreement Sections</h4>
                            {sections.map((section, idx) => (
                                <a
                                    key={idx}
                                    href={`#section-${idx}`}
                                    className="block px-4 py-2 text-sm font-medium text-gray-600 dark:text-gray-400 hover:text-blue-600 dark:hover:text-blue-400 hover:bg-blue-50 dark:hover:bg-blue-900/20 rounded-lg transition-all"
                                >
                                    {section.title.split('. ')[1]}
                                </a>
                            ))}
                        </div>
                    </div>

                    {/* Main Terms Content */}
                    <div className="lg:col-span-3 space-y-16">
                        <div className="prose dark:prose-invert max-w-none">
                            <p className="text-sm text-gray-500 italic mb-10">
                                These terms constitute a legally binding agreement between you and ai for job regarding your use of the platform and services.
                            </p>
                        </div>

                        {sections.map((section, idx) => (
                            <section key={idx} id={`section-${idx}`} className="scroll-mt-32 group">
                                <div className="flex items-center space-x-4 mb-6">
                                    <div className="w-12 h-12 rounded-2xl bg-white dark:bg-gray-900 shadow-sm border border-gray-200 dark:border-gray-800 flex items-center justify-center group-hover:border-blue-500/50 transition-colors">
                                        {section.icon}
                                    </div>
                                    <h2 className="text-2xl font-bold text-gray-900 dark:text-white tracking-tight">
                                        {section.title}
                                    </h2>
                                </div>
                                <div className="text-gray-600 dark:text-gray-400 leading-relaxed pl-16">
                                    {section.content}
                                </div>
                            </section>
                        ))}

                        {/* Assistance Section */}
                        <div className="mt-20 p-8 rounded-3xl bg-slate-900 border border-slate-800 text-white relative overflow-hidden">
                            <div className="relative z-10">
                                <div className="flex items-center space-x-3 mb-6">
                                    <HelpCircle className="w-6 h-6 text-blue-400" />
                                    <h3 className="text-2xl font-bold">Need legal clarification?</h3>
                                </div>
                                <p className="text-slate-400 mb-8 max-w-lg">If you have any questions regarding these terms, our billing processes with Stripe/Razorpay, or your account, please reach out to us.</p>
                                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                    <div className="flex items-center space-x-3 bg-white/5 p-4 rounded-xl border border-white/10 hover:border-blue-500/30 transition-colors group">
                                        <Mail className="w-5 h-5 text-blue-400" />
                                        <span className="text-sm font-medium">info@aiforjob.ai</span>
                                    </div>
                                    <div className="flex items-center space-x-3 bg-white/5 p-4 rounded-xl border border-white/10 hover:border-blue-500/30 transition-colors group">
                                        <Phone className="w-5 h-5 text-blue-400" />
                                        <span className="text-sm font-medium">+91 83077 17793</span>
                                    </div>
                                </div>
                                <div className="mt-6 flex items-center space-x-3 bg-white/5 p-4 rounded-xl border border-white/10">
                                    <MapPin className="w-5 h-5 text-blue-400" />
                                    <span className="text-sm font-medium uppercase tracking-tight">A-30 Max Heights, Sonepat, Haryana, India</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default TermsOfService;
